name: Deploy Site

on:
  push:
    paths: 
      - 'docs/**'
      - 'mkdocs.yml'
      - 'theme/**'
    branches:
      - master

permissions:
  contents: write   # allows pushing to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      
      - name: Create virtual environment
        run: python -m venv .venv
      
      - name: Activate virtual environment
        shell: bash
        run: source .venv/bin/activate

      - name: Install dependencies
        shell: bash
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip setuptools wheel
          pip install mkdocs-material
          pip install pymdown-extensions>=10.16.1
          pip install -r requirements.txt
          pip install -e obsidian_interactive_graph/


          
      - name: Deploy Site
        shell: bash
        run: |
          source .venv/bin/activate
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          mkdocs gh-deploy --force

