name: Deploy Site

on:
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'theme/**'
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        run: python -m venv .venv

      - name: Activate venv and install deps
        shell: bash
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip setuptools wheel
          # Install Pymdown first to guarantee wikilinks is available
          python -m pip install "pymdown-extensions>=10.16.1"
          python -m pip install mkdocs-material==9.6.18
          # Install your plugin using PEP517
          python -m pip install --use-pep517 -e obsidian_interactive_graph/

      - name: Deploy MkDocs
        shell: bash
        run: |
          source .venv/bin/activate
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          mkdocs gh-deploy --force
