name: Deploy Site

on:
  push:
    paths: 
      - 'docs/**'
      - 'mkdocs.yml'
      - 'theme/**'
    branches:
      - master

permissions:
  contents: write   # allows pushing to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install mkdocs-material
          pip install mkdocs-obsidian-interactive-graph-plugin
          pip install mkdocs-obsidian-bridge  # handles [[wikilinks]] now
          pip install -r requirements.txt

      - name: Deploy Site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          mkdocs gh-deploy --force
