name: Deploy Site

on:
  push:
    paths: 
      - 'docs/**'
      - 'mkdocs.yml'
      - 'theme/**'
    branches:
      - master

permissions:
  contents: write   # allows pushing to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Create and activate virtual environment
      - name: Setup Python
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip setuptools wheel

      # Install dependencies inside the venv
      - name: Install dependencies
        run: |
          source .venv/bin/activate
          pip install mkdocs-material==9.6.18
          pip install pymdown-extensions>=10.16.1
          pip install -r requirements.txt
          # Editable install of your local plugin
          pip install -e obsidian_interactive_graph/

      # Deploy the site using MkDocs inside the same venv
      - name: Deploy Site
        run: |
          source .venv/bin/activate
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          mkdocs gh-deploy --force
