name: Deploy Site

on:
  push:
    paths: 
      - 'docs/**'
      - 'mkdocs.yml'
      - 'theme/**'
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python and deploy
        run: |
          python -m venv .venv
          . .venv/bin/activate

          pip install --upgrade pip setuptools wheel
          pip install mkdocs-material==9.6.18
          pip install pymdown-extensions>=10.16.1
          pip install -r requirements.txt

          # Install local plugin in editable mode
          pip install -e obsidian_interactive_graph/

          # Configure git and deploy
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          mkdocs gh-deploy --force
